export const AJOUTE_INSCRIPTION_SUCCES="AJOUTE_INSCRIPTION_SUCCES"
export const AJOUTE_INSCRIPTION_DEMANDE="AJOUTE_INSCRIPTION_DEMANDE"
export const AJOUTE_INSCRIPTION_ECHEC="AJOUTE_INSCRIPTION_ECHEC"
export const ISNSCRIPTION="INSCRIPTION"

//types validation pharmacie
export const AFFICHE_LIST_PHARMACIES_SUCCES="AFFICHE_LIST_PHARMACIE_SUCCES"
export const AFFICHE_LIST_PHARMACIES_DEMANDE = "AFFICHE_LIST_PHARMACIES_DEMANDE"
export const AFFICHE_LIST_PHARMACIES_ECHEC = "AFFICHE_LIST_PHARMACIES_ECHEC"

//types connexion pharmacie
export const PHARMACIE_LOADED="PHARMACIE_LOADED"
export const CONNEXION_PHARMACIES_SUCCES="CONNEXION_PHARMACIE_SUCCES"
export const CONNEXION_PHARMACIES_DEMANDE = "CONNEXION_PHARMACIES_DEMANDE"
export const CONNEXION_PHARMACIES_ECHEC = "CONNEXION_PHARMACIES_ECHEC"
export const CONNEXION_ERROR = 'CONNEXION_ERROR'
export const LOGOUT = 'LOGOUT'


//types admin
export const ADMIN_LOADED="ADMIN_LOADED"
export const ADMIN_SUCCES="ADMIN_SUCCES"
export const ADMIN_DEMANDE="ADMIN_DEMANDE"
export const ADMIN_ECHEC="ADMIN_ECHEC"
export const ADMIN_CONNEXION_ERROR = "ADMIN_CONNEXION_ERROR"
export const ADMIN_LOGOUT = "ADMIN_LOGOUT"

//types gestion centre
export const AJOUTE_CENTRE_SUCCES="AJOUTE_CENTRE_SUCCES"
export const AJOUTE_CENTRE_DEMANDE="AJOUTE_CENTRE_DEMANDE"
export const AJOUTE_CENTRE_ECHEC="AJOUTE_CENTRE_ECHEC"
//type supprime centre
export const SUPPRIMER_CENTRE_SUCCES="SUPPRIMER_CENTRE_SUCCES"
export const SUPPRIMER_CENTRE_DEMANDE="SUPPRIMER_CENTRE_DEMANDE"
export const SUPPRIMER_CENTRE_ECHEC="SUPPRIMER_CENTRE_ECHEC"
//type modifier centre
export const MODIFIER_CENTRE_SUCCES="MODIFIER_CENTRE_SUCCES"
export const MODIFIER_CENTRE_DEMANDE="MODIFIER_CENTRE_DEMANDE"
export const MODIFIER_CENTRE_ECHEC="MODIFIER_CENTRE_ECHEC"
//type selectionne centre
export const SET_SELECTED_CENTRE="SET_SELECTED_CENTRE"
export const AFFICHE_CENTRE_DEMANDE="AFFICHE_CENTRE_DEMANDE"
export const AFFICHE_CENTRE_SUCCES="AFFICHE_CENTRE_SUCCES"
export const AFFICHE_CENTRE_ECHEC="AFFICHE_CENTRE_ECHEC"


//types gestion vaccin
export const AJOUTE_VACCIN_SUCCES="AJOUTE_VACCIN_SUCCES"
export const AJOUTE_VACCIN_DEMANDE="AJOUTE_VACCIN_DEMANDE"
export const AJOUTE_VACCIN_ECHEC="AJOUTE_VACCIN_ECHEC"
//type supprime vaccin
export const SUPPRIMER_VACCIN_SUCCES="SUPPRIMER_VACCIN_SUCCES"
export const SUPPRIMER_VACCIN_DEMANDE="SUPPRIMER_VACCIN_DEMANDE"
export const SUPPRIMER_VACCIN_ECHEC="SUPPRIMER_VAVCCIN_ECHEC"
//type modifier vaccin
export const MODIFIER_VACCIN_SUCCES="MODIFIER_VACCIN_SUCCES"
export const MODIFIER_VACCIN_DEMANDE="MODIFIER_VACCIN_DEMANDE"
export const MODIFIER_VACCIN_ECHEC="MODIFIER_VACCIN_ECHEC"
//type selectionne vaccin
export const SET_SELECTED_VACCIN="SET_SELECTED_VACCIN"
export const AFFICHE_VACCIN_DEMANDE="AFFICHE_VACCIN_DEMANDE"
export const AFFICHE_VACCIN_SUCCES="AFFICHE_VACCIN_SUCCES"
export const AFFICHE_VACCIN_ECHEC="AFFICHE_VACCIN_ECHEC"
//types list centres
export const AFFICHE_LIST_VACCINS_SUCCES="AFFICHE_LIST_VACCINS_SUCCES"
export const AFFICHE_LIST_VACCINS_DEMANDE = "AFFICHE_LIST_VACCINS_DEMANDE"
export const AFFICHE_LIST_VACCINS_ECHEC = "AFFICHE_LIST_VACCINS_ECHEC"

//types affiche pharamcie
export const AFFICHE_PHARMACIE_DEMANDE="AFFICHE_PHARMACIE_DEMANDE"
export const AFFICHE_PHARMACIE_SUCCES="AFFICHE_PHARMACIE_SUCCES"
export const AFFICHE_PHARMACIE_ECHEC="AFFICHE_PHARMACIE_ECHEC"
//types modifier pharamcie
export const MODIFIER_PHARMACIE_DEMANDE="MODIFIER_PHARMACIE_DEMANDE"
export const MODIFIER_PHARMACIE_SUCCES="MODIFIER_PHARMACIE_SUCCES"
export const MODIFIER_PHARMACIE_ECHEC="MODIFIER_PHARMACIE_ECHEC"
//types select pharamcie
export const SET_SELECTED_PHARMACIE="SET_SELECTED_PHARMACIE"
//types summprimer pharamcie
export const SUPPRIMER_PHARMACIE_SUCCES="SUPPRIMER_PHARMACIE_SUCCES"
export const SUPPRIMER_PHARMACIE_DEMANDE="SUPPRIMER_PHARMACIE_DEMANDE"
export const SUPPRIMER_PHARMACIE_ECHEC="SUPPRIMER_PHARMACIE_ECHEC"
//types list centres
export const AFFICHE_LIST_CENTRES_SUCCES="AFFICHE_LIST_CENTRES_SUCCES"
export const AFFICHE_LIST_CENTRES_DEMANDE = "AFFICHE_LIST_CENTRES_DEMANDE"
export const AFFICHE_LIST_CENTRES_ECHEC = "AFFICHE_LIST_CENTRES_ECHEC"


//types affectation vaccin
export const AJOUTE_AFFECTATION_SUCCES="AJOUTE_AFFECTATION_SUCCES"
export const AJOUTE_AFFECTATION_DEMANDE="AJOUTE_AFFECTATION_DEMANDE"
export const AJOUTE_AFFECTATION_ECHEC="AJOUTE_AFFECTATION_ECHEC"

//types validation inscription
export const AJOUTE_VALIDATION_SUCCES="AJOUTE_VALIDATION_SUCCES"
export const AJOUTE_VALIDATION_DEMANDE="AJOUTE_VALIDATION_DEMANDE"
export const AJOUTE_VALIDATION_ECHEC="AJOUTE_VALIDATION_ECHEC"
//types list inscriptions
export const AFFICHE_LIST_INSCRIPTIONS_SUCCES="AFFICHE_LIST_INSCRIPTIONS_SUCCES"
export const AFFICHE_LIST_INSCRIPTIONS_DEMANDE = "AFFICHE_LIST_INSCRIPTIONS_DEMANDE"
export const AFFICHE_LIST_INSCRIPTIONS_ECHEC = "AFFICHE_LIST_INSCRIPTIONS_ECHEC"
//types affiche inscription
export const AFFICHE_INSCRIPTION_DEMANDE="AFFICHE_INSCRIPTION_DEMANDE"
export const AFFICHE_INSCRIPTION_SUCCES="AFFICHE_INSCRIPTION_SUCCES"
export const AFFICHE_INSCRIPTION_ECHEC="AFFICHE_INSCRIPTION_ECHEC"
export const SET_SELECTED_INSCRIPTION="SET_SELECTED_INSCRIPTION"

//types gestion volontaire
export const AJOUTE_VOLONTAIRE_SUCCES="AJOUTE_VOLONTAIRE_SUCCES"
export const AJOUTE_VOLONTAIRE_DEMANDE="AJOUTE_VOLONTAIRE_DEMANDE"
export const AJOUTE_VOLONTAIRE_ECHEC="AJOUTE_VOLONTAIRE_ECHEC"
//type supprimer volontaire
export const SUPPRIMER_VOLONTAIRE_SUCCES="SUPPRIMER_VOLONTAIRE_SUCCES"
export const SUPPRIMER_VOLONTAIRE_DEMANDE="SUPPRIMER_VOLONTAIRE_DEMANDE"
export const SUPPRIMER_VOLONTAIRE_ECHEC="SUPPRIMER_VOLONTAIRE_ECHEC"
//type modifier volontaire
export const MODIFIER_VOLONTAIRE_SUCCES="MODIFIER_VOLONTAIRE_SUCCES"
export const MODIFIER_VOLONTAIRE_DEMANDE="MODIFIER_VOLONTAIRE_DEMANDE"
export const MODIFIER_VOLONTAIRE_ECHEC="MODIFIER_VOLONTAIRE_ECHEC"
//type selectionne volontaire
export const SET_SELECTED_VOLONTAIRE="SET_SELECTED_VOLONTAIRE"
export const AFFICHE_VOLONTAIRE_DEMANDE="AFFICHE_VOLONTAIRE_DEMANDE"
export const AFFICHE_VOLONTAIRE_SUCCES="AFFICHE_VOLONTAIRE_SUCCES"
export const AFFICHE_VOLONTAIRE_ECHEC="AFFICHE_VOLONTAIRE_ECHEC"
//types list volontaire
export const AFFICHE_LIST_VOLONTAIRES_SUCCES="AFFICHE_LIST_VOLONTAIRES_SUCCES"
export const AFFICHE_LIST_VOLONTAIRES_DEMANDE = "AFFICHE_LIST_VOLONTAIRES_DEMANDE"
export const AFFICHE_LIST_VOLONTAIRES_ECHEC = "AFFICHE_LIST_VOLONTAIRES_ECHEC"


//types gestion jpo
export const AJOUTE_JPO_SUCCES="AJOUTE_JPO_SUCCES"
export const AJOUTE_JPO_DEMANDE="AJOUTE_JPO_DEMANDE"
export const AJOUTE_JPO_ECHEC="AJOUTE_JPO_ECHEC"
//type supprimer jpo
export const SUPPRIMER_JPO_SUCCES="SUPPRIMER_JPO_SUCCES"
export const SUPPRIMER_JPO_DEMANDE="SUPPRIMER_JPO_DEMANDE"
export const SUPPRIMER_JPO_ECHEC="SUPPRIMER_JPO_ECHEC"
//type modifier jpo
export const MODIFIER_JPO_SUCCES="MODIFIER_JPO_SUCCES"
export const MODIFIER_JPO_DEMANDE="MODIFIER_JPO_DEMANDE"
export const MODIFIER_JPO_ECHEC="MODIFIER_JPO_ECHEC"
//type selectionne jpo
export const SET_SELECTED_JPO="SET_SELECTED_JPO"
export const AFFICHE_JPO_DEMANDE="AFFICHE_JPO_DEMANDE"
export const AFFICHE_JPO_SUCCES="AFFICHE_JPO_SUCCES"
export const AFFICHE_JPO_ECHEC="AFFICHE_JPO_ECHEC"
//types list jpo
export const AFFICHE_LIST_JPOS_SUCCES="AFFICHE_LIST_JPO_SUCCES"
export const AFFICHE_LIST_JPOS_DEMANDE = "AFFICHE_LIST_JPO_DEMANDE"
export const AFFICHE_LIST_JPOS_ECHEC = "AFFICHE_LIST_JPO_ECHEC"




//types gestion citoyen
export const AJOUTE_CITOYEN_SUCCES="AJOUTE_CITOYEN_SUCCES"
export const AJOUTE_CITOYEN_DEMANDE="AJOUTE_CITOYEN_DEMANDE"
export const AJOUTE_CITOYEN_ECHEC="AJOUTE_CITOYEN_ECHEC"
//type selectionne citoyen
export const SET_SELECTED_CITOYEN="SET_SELECTED_CITOYEN"
export const AFFICHE_CITOYEN_DEMANDE="AFFICHE_CITOYEN_DEMANDE"
export const AFFICHE_CITOYEN_SUCCES="AFFICHE_CITOYEN_SUCCES"
export const AFFICHE_CITOYEN_ECHEC="AFFICHE_CITOYEN_ECHEC"
//types list citoyen
export const AFFICHE_LIST_CITOYENS_SUCCES="AFFICHE_LIST_CITOYENS_SUCCES"
export const AFFICHE_LIST_CITOYENS_DEMANDE = "AFFICHE_LIST_CITOYENS_DEMANDE"
export const AFFICHE_LIST_CITOYENS_ECHEC = "AFFICHE_LIST_CITOYENS_ECHEC"



export const CONNEXION_VISITEURS_SUCCES="CONNEXION_VISITEUR_SUCCES"
export const CONNEXION_VISITEURS_DEMANDE = "CONNEXION_VISITEURS_DEMANDE"
export const CONNEXION_VISITEURS_ECHEC = "CONNEXION_VISITEUR_ECHEC"
export const CONNEXIONS_ERRORS = 'CONNEXIONS_ERRORS'
export const LOGOUT_VISITEUR = 'LOGOUT_VISITEUR'
export const VISITEUR_LOADED="VISITEUR_LOADED"



//type mettre à jour inscription ameni
export const METTREJOUR_INSCRIPTION_DEMANDE="METTREJOUR_INSCRIPTION_DEMANDE"
export const METTREJOUR_INSCRIPTION_SUCCES="METTREJOUR_INSCRIPTION_SUCCES"
export const METTREJOUR_INSCRIPTION_ECHEC="METTREJOUR_INSCRIPTION_ECHEC"

//type raportez rendez-vous
export const RAPORTERRENDEZVOUS_INSCRIPTION_DEMANDE="RAPORTERRENDEZVOUS_INSCRIPTION_DEMANDE"
export const RAPORTERRENDEZVOUS_INSCRIPTION_SUCCES="RAPORTERRENDEZVOUS_INSCRIPTION_SUCCES"
export const RAPORTERRENDEZVOUS_INSCRIPTION_ECHEC="RAPORTERRENDEZVOUS_INSCRIPTION_ECHEC"

//types gestion centre
export const AJOUTE_RENDEZVOUS_SUCCES="AJOUTE_RENDEZVOUS_SUCCES"
export const AJOUTE_RENDEZVOUS_DEMANDE="AJOUTE_RENDEZVOUS_DEMANDE"
export const AJOUTE_RENDEZVOUS_ECHEC="AJOUTE_RENDEZVOUS_ECHEC"
//type supprime RENDEZVOUS
export const SUPPRIMER_RENDEZVOUS_SUCCES="SUPPRIMER_RENDEZVOUS_SUCCES"
export const SUPPRIMER_RENDEZVOUS_DEMANDE="SUPPRIMER_RENDEZVOUS_DEMANDE"
export const SUPPRIMER_RENDEZVOUS_ECHEC="SUPPRIMER_RENDEZVOUS_ECHEC"
//type modifier RENDEZVOUS
export const MODIFIER_RENDEZVOUS_SUCCES="MODIFIER_RENDEZVOUS_SUCCES"
export const MODIFIER_RENDEZVOUS_DEMANDE="MODIFIER_RENDEZVOUS_DEMANDE"
export const MODIFIER_RENDEZVOUS_ECHEC="MODIFIER_RENDEZVOUS_ECHEC"
//type selectionne RENDEZVOUS
export const SET_SELECTED_RENDEZVOUS="SET_SELECTED_RENDEZVOUS"
export const AFFICHE_RENDEZVOUS_DEMANDE="AFFICHE_RENDEZVOUS_DEMANDE"
export const AFFICHE_RENDEZVOUS_SUCCES="AFFICHE_RENDEZVOUS_SUCCES"
export const AFFICHE_RENDEZVOUS_ECHEC="AFFICHE_RENDEZVOUS_ECHEC"
//types list centres
export const AFFICHE_LIST_RENDEZVOUSS_SUCCES="AFFICHE_LIST_RENDEZVOUSS_SUCCES"
export const AFFICHE_LIST_RENDEZVOUSS_DEMANDE = "AFFICHE_LIST_RENDEZVOUSS_DEMANDE"
export const AFFICHE_LIST_RENDEZVOUSS_ECHEC = "AFFICHE_LIST_CENTRES_ECHEC"


//types list centres
export const AFFICHE_LIST_VISITEURS_SUCCES="AFFICHE_LIST_VISITEURS_SUCCES"
export const AFFICHE_LIST_VISITEURS_DEMANDE = "AFFICHE_LIST_VISITEURS_DEMANDE"
export const AFFICHE_LIST_VISITEURS_ECHEC = "AFFICHE_LIST_VISITEURS_ECHEC"

//types gestion centre
export const AJOUTE_AFFECTATION_RENDEZVOUS_DEMANDE="AJOUTE_AFFECTATION_RENDEZVOUS_DEMANDE"
export const AJOUTE_AFFECTATION_RENDEZVOUS_SUCCES="AJOUTE_AFFECTATION_RENDEZVOUS_SUCCES"
export const AJOUTE_AFFECTATION_RENDEZVOUS_ECHEC="AJOUTE_AFFECTATION_RENDEZVOUS_ECHEC"

